use_frameworks!

platform :ios, '9.0'

target 'CustomFeedbackForm_Example' do
  pod 'CustomFeedbackForm', :path => '../'

  target 'CustomFeedbackForm_Tests' do
    inherit! :search_paths

    
  end
end
